# Generated by Django 5.1.4 on 2025-02-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_clients', '0004_rename_client_type_idx_management__client__95b1f0_idx_and_more'),
        ('management_properties', '0002_property_current_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=0, help_text='Monthly rent amount', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=0, help_text="Agent's commission amount", max_digits=10)),
                ('start_date', models.DateField(help_text='When the rental agreement begins')),
                ('end_date', models.DateField(blank=True, help_text='When the rental agreement ends (if applicable)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rental agreement is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The client who owns the property', on_delete=django.db.models.deletion.PROTECT, related_name='properties_rented_out', to='management_clients.client')),
                ('property', models.ForeignKey(help_text='The property being rented', on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to='management_properties.property')),
                ('tenant', models.ForeignKey(help_text='The client who is renting the property', on_delete=django.db.models.deletion.PROTECT, related_name='properties_rented', to='management_clients.client')),
            ],
            options={
                'verbose_name': 'Rental Agreement',
                'verbose_name_plural': 'Rental Agreements',
                'ordering': ['-is_active', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(help_text='Year of this rental period')),
                ('period_month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Month of this rental period (1-12)')),
                ('rent_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('late', 'Late'), ('unpaid', 'Unpaid')], default='pending', help_text='Current status of the rent payment', max_length=10)),
                ('payment_date', models.DateField(blank=True, help_text='When the rent was paid', null=True)),
                ('transfer_amount', models.DecimalField(decimal_places=0, help_text='Amount to be transferred to owner', max_digits=10)),
                ('transfer_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', help_text='Current status of the transfer to owner', max_length=10)),
                ('transfer_date', models.DateField(blank=True, help_text='When the transfer to owner was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_agreement', models.ForeignKey(help_text='The associated rental agreement', on_delete=django.db.models.deletion.PROTECT, related_name='monthly_rentals', to='management_rentals.rentalagreement')),
            ],
            options={
                'verbose_name': 'Monthly Rental',
                'verbose_name_plural': 'Monthly Rentals',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('rental_agreement', 'period_year', 'period_month')},
            },
        ),
    ]
