# Generated by Django 5.1.4 on 2025-01-20 14:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the property owner', max_length=200)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the client currently has any properties listed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Owner',
                'verbose_name_plural': 'Property Owners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date when ownership began')),
                ('end_date', models.DateField(blank=True, help_text='Date when ownership ended (if applicable)', null=True)),
                ('owner', models.ForeignKey(help_text='The owner of the property', on_delete=django.db.models.deletion.CASCADE, related_name='property_history', to='management_clients.client')),
                ('property', models.ForeignKey(help_text='The property being owned', on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='management_properties.property')),
            ],
            options={
                'verbose_name': 'Property Ownership',
                'verbose_name_plural': 'Property Ownerships',
                'ordering': ['-start_date'],
            },
        ),
    ]
