# Generated by Django 5.1.4 on 2025-01-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_clients', '0003_set_existing_clients_as_owners'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='management__client__95b1f0_idx',
            old_name='client_type_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the client is currently active in the system'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Full name of the client', max_length=200),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='owner',
            field=models.ForeignKey(help_text='The owner of the property', limit_choices_to={'client_type': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='property_history', to='management_clients.client'),
        ),
    ]
